/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codingpan;

public class AlgorithmPractice {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new AlgorithmPracticeApp().getGreeting());
    }
}
